name: clima_ufg
description: "Projeto Clima UFG do minicurso Mobile Week 2.0."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#FCFCFC"
  image: assets/emoji_logo.png
  branding: assets/emoji_logo.png
  color_dark: "#FCFCFC"
  image_dark: assets/emoji_logo.png
  branding_dark: assets/emoji_logo.png

  android_12:
    image: assets/emoji_logo.png
    icon_background_color: "#FCFCFC"
    image_dark: assets/emoji_logo.png
    icon_background_color_dark: "#FCFCFC"

  web: false

flutter_launcher_icons:
  flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/emoji_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:
  uses-material-design: true

  assets:
    - assets/menu_superior.png
    - assets/pin.png
    - assets/emoji_logo.png
    - .env
